### ISSUE TITLE
arbitrary expressions in key-value attributes are unstable

### ISSUE THREAD

**Issue by aliemjay** [la10736/rstest#117]
The key-value attributes, which are used by the new syntax (#99), accept only literals on stable compiler. Trying to use any other expression yields the following error message:

error[E0658]: arbitrary expressions in key-value attributes are unstable
note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

This makes it impossible to set trivial defaults such as `None` or `&[]`.

Here is the test code:
```rust
// rustc 1.51
// rstest 0.7.0
use rstest::{fixture, rstest};

// Old syntax is OK
#[fixture(val=1+1)]
fn echo(val: i32) -> i32 {
    val
}

// New syntax fails
#[fixture]
fn echo2(#[default=1+1] val: i32) -> i32 {
    val
}

```

**Comment by la10736** [comment]
Ok, I missed it. I'll switch to `#[deafult( 1 + 1 )]` syntax till the syntax become stable.
