### ISSUE TITLE
Nightly detection does not take into account whether features can actually be used

### ISSUE THREAD

**Issue by jonhoo** [la10736/rstest#126]
Currently, the build script just checks [whether the user is using nightly](https://github.com/la10736/rstest/blob/3e6648aa5df2e49bebeab1900eff6ef42279c8f6/build.rs#L7-L9), but that doesn't work when the user's configuration, other flags, or the rustc wrapper, prevent the use of the relevant features:

```bash
cargo new rstest-issue
cd rstest-issue
mkdir .cargo
echo '[build]' >> .cargo/config.toml
echo 'rustflags = ["-Zallow-features="]' >> .cargo/config.toml
echo 'rstest = "0.6"' >> Cargo.toml
rustup override set nightly
cargo check
```

produces

```
   Compiling rstest v0.6.4
error[E0725]: the feature `proc_macro_span` is not in the list of allowed features
  --> /Users/jongje/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.27/src/lib.rs:82:59
   |
82 | #![cfg_attr(any(proc_macro_span, super_unstable), feature(proc_macro_span))]
   |                                                           ^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'proc_macro_span'
   --> /Users/jongje/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.27/src/wrapper.rs:517:72
    |
517 |             (Span::Compiler(a), Span::Compiler(b)) => Span::Compiler(a.join(b)?),
    |                                                                        ^^^^
    |
    = note: see issue #54725 <https://github.com/rust-lang/rust/issues/54725> for more information
    = help: add `#![feature(proc_macro_span)]` to the crate attributes to enable
...
```

The `proc-macro2` crate specifically tries to handle this by [parsing `RUSTFLAGS` if set](https://github.com/alexcrichton/proc-macro2/blob/e71bc70db21eb6f217d8ed9f8ece0d53ba7cfac5/build.rs#L128), though that currently also runs into issues (https://github.com/alexcrichton/proc-macro2/issues/290). The `anyhow` crate uses a "[compile probe](https://github.com/dtolnay/anyhow/blob/88f25d809d0148dea13d6f56c3b381aa98735801/build.rs#L65)", which is very robust, but currently suffers from lack of information from Cargo (https://github.com/dtolnay/anyhow/issues/156). But once https://github.com/rust-lang/cargo/pull/9601 lands, we'll have access to the necessary configuration information to check for feature support using either of those two approaches.

I filed this here (in addition to `proc-macro2`) because once `proc-macro2` is fixed, cookie will start breaking with the same reproduction steps due to this `build.rs`:
https://github.com/la10736/rstest/blob/3e6648aa5df2e49bebeab1900eff6ef42279c8f6/build.rs#L7-L9

You can see that by changing the instructions above to `-Zallow-features=proc_macro_span`:
```console
$ cargo check
   Compiling rstest v0.6.4
error[E0725]: the feature `proc_macro_diagnostic` is not in the list of allowed features
   --> /Users/jongje/.cargo/registry/src/github.com-1ecc6299db9ec823/rstest-0.6.4/src/lib.rs:213:48
    |
213 | #![cfg_attr(use_proc_macro_diagnostic, feature(proc_macro_diagnostic))]
    |                                                ^^^^^^^^^^^^^^^^^^^^^
```

See also https://github.com/SergioBenitez/cookie-rs/issues/177.

**Comment by la10736** [comment]
Thanks very much. I'll update my code to use when it land.

**Comment by jonhoo** [comment]
Honestly, I'd recommend instead using something like @cuviper's [`autocfg`](https://crates.io/crates/autocfg), which will implement the logic for you :) There's also [`version_check`](https://crates.io/crates/version_check) which doesn't _currently_ implement the logic for "is this specific feature available", but [will do so soon](https://github.com/SergioBenitez/cookie-rs/issues/177#issuecomment-875173361).

**Comment by jonhoo** [comment]
You can now parse `CARGO_ENCODED_RUSTFLAGS`, which is provided by nightly cargo and will be on the next beta (rust-lang/cargo#9601).

**Comment by la10736** [comment]
I choose to implement `CARGO_ENCODED_RUSTFLAGS` parsing because autocfg don't implement the feature probing that I need and the [pull request](https://github.com/cuviper/autocfg/pull/35) stuck from a while.  Also version_check haven't any plan to implement it soon.
