### ISSUE TITLE
rstest try to use case argument as fixture if preceded by underscore

### ISSUE THREAD

**Issue by raffomania** [la10736/rstest#130]
We have a `Factory` trait for functions that create entities in our database. This trait is implemented for different entities and then applied using rstest_reuse:

```rs
#[template]
#[rstest(api)]
#[case::sites(PostFactory {})]
#[case::user_tag_assignments(UserFactory {})]
// ...
pub fn apis<T: Factory>(#[case] api: T) {}
```

However, this trait only contains associated functions and no state, so we end up calling the functions in tests using assiciated function syntax (simplified example):
```rs
#[apply(apis)]
#[tokio::test]
async fn is_correct<T: Factory>(
    api: T,
) -> Result<()> {
    T::create_entity("name", "id").await?;
```

With this, the compiler complains that the `factory` argument is unused. When prefixing it with an underscore, the `rstest` macro seems to generate invalid code:

```rs
#[template]
#[rstest(_api)]
#[case::sites(PostFactory {})]
#[case::user_tag_assignments(UserFactory {})]
// ...
pub fn apis<T: Factory>(#[case] _api: T) {}
```

```
error[E0433]: failed to resolve: use of undeclared crate or module `api`
   --> mod.rs:321:65
    |
321 | async fn is_correct<T: Factory>(_api: T) -> Result<()> {
    |                                 ^^^^ use of undeclared crate or module `api`
```

Is there another way to solve this on our end? I'm open to restructuring the code if there's a better way to do it.

Alternatively, it would be great to have support for unused arguments in rstest_reuse templates.

**Comment by la10736** [comment]
Try follow:
```rust
#[template]
#[rstest]
#[case::sites(PostFactory {})]
#[case::user_tag_assignments(UserFactory {})]
pub fn apis<T: Factory>(#[case] api: T) {}

#[apply(apis)]
#[tokio::test]
async fn is_correct<T: Factory>(
    #[case] _api: T,
) -> Result<()> {
    T::create_entity("name", "id").await?;
}
```

In the first snipped you're mixing compact and attribute syntax. `rstest_reuse` don't (yet) replicate the function template signature attributes so you need to mark case arguments in any tests.

Maybe I need to update `rstest_reuse` documentation to explain better how to use it with the newer syntax.

**Comment by raffomania** [comment]
Interesting, I've updated to use the new syntax but still get the exact same error. I can provide a minimal reproduction repo for testing, if you'd like?

**Comment by la10736** [comment]
Yes, thanks!!

**Comment by raffomania** [comment]
[Here you go](https://github.com/raffomania/rstest-template-unused-variables-demo)! Running `cargo test` in the repo should show you the error.

**Comment by raffomania** [comment]
Running cargo expand on that example shows the following line:
```rs
fn case_1_users() -> () {
        let _api = api::default();
        // ...
```

This seems to be the source of the error.

**Comment by la10736** [comment]
That seams a bug in `rstest`. It's trying to resolve `_api` as fixture and not as argument:

```rust
#[rstest]
#[case::users(UserFactory {})]
pub fn more<T: Factory>(#[case] _api: T) {
    assert_eq!(T::foo(), "foo");
}
```

Trigger the same error.

Unfortunately you can just do one of

1. Add `#![allow(unused_variables)]` at the top of your test file
2.  Add `let _ = &api;` as first line of your tests

Both of them are really dirty but I cannot fix it in the next days :(

**Comment by raffomania** [comment]
Thanks for your help! I'll work around the issue for now. Glad we could pin it down :)
