### ISSUE TITLE
once fixtures don't get Dropped

### ISSUE THREAD

**Issue by vpzomtrrfrt** [la10736/rstest#132]
Example:

```rust
use rstest::*;

struct SomeStruct {}
impl std::ops::Drop for SomeStruct {
    fn drop(&mut self) {
        std::fs::File::create("got_dropped").unwrap();
    }
}

#[fixture]
#[once]
fn value() -> SomeStruct {
    std::fs::File::create("got_created").unwrap();
    SomeStruct {}
}

#[rstest]
fn test1(value: &SomeStruct) {
    assert!(true);
}
```

Running this test creates the "got_created" file but not the "got_dropped" file, indicating that the Drop implementation for SomeStruct was not run

**Comment by la10736** [comment]
I'm sorry, but this is a well know limitation of this implementation (https://github.com/la10736/rstest/issues/119#issuecomment-841658846). You can find a note about this at https://docs.rs/rstest/latest/rstest/attr.fixture.html#once-fixture .
I think that there is no way to implement it without write a custom test runner that will make this crate harder to use.

**Comment by vpzomtrrfrt** [comment]
ah I missed that note, fair enough
