### ISSUE TITLE
should_panic doesn't work for the entire test suite

### ISSUE THREAD

**Issue by yegor256** [la10736/rstest#134]
This is what I tried to do:

```rust
#[rstest]
#[should_panic]
#[case("incorrect syntax")]
#[case("another example of incorrect syntax")]
pub fn fails_on_incorrect_syntax(input : String) {
    try_it(&input);
}
```

It doesn't work.

Instead, I have to do this:

```rust
#[rstest(input,
  #[should_panic] case("incorrect syntax"),
  #[should_panic] case("another example of incorrect syntax"))]
pub fn fails_on_incorrect_path(input : String) {
    try_it(&input);
}
```

What is the right way and the most compact one?

**Comment by la10736** [comment]
Attributes before function definition will be applied to all tests (https://docs.rs/rstest/latest/rstest/attr.rstest.html#use-specific-case-attributes last paragraph). The most compact syntax for your tests is:

```rust
#[rstest]
#[case("incorrect syntax")]
#[case("another example of incorrect syntax")]
#[should_panic]
pub fn fails_on_incorrect_syntax(input : String) {
    try_it(&input);
}
```

A simple way to remember that is "all attributes before a test case will be applied to the case and all attributes before function will be applied to the test function"

**Comment by la10736** [comment]
One more thing: you can also use 

```rust
#[rstest(input,
  case("incorrect syntax"),
  case("another example of incorrect syntax"))]
#[should_panic] 
pub fn fails_on_incorrect_path(input : String) {
    try_it(&input);
}
```

with the same result ... but I think that the attribute based syntax is more clear and maybe the old syntax should be deprecated.

**Comment by la10736** [comment]
Can I close this ticket?

**Comment by yegor256** [comment]
@la10736 thanks for the answer, great lib!
