### ISSUE TITLE
Support multiple templates per test case

### ISSUE THREAD

**Issue by asomers** [la10736/rstest#138]
`rstest_reuse` is great for reusing lists of test cases.  But what I would really like to do would be to combine multiple templates on one test function, in order to test with the cartesian product of all specified fixtures.  Something like this:
```rust
#[template]
#[rstest(q,
    case(false),
    case(true)
)]
fn bools(#[case] q: bool) {}
#[template]
#[rstest(x,
    case(0),
    case(1),
    case(2),
)]
fn ints(#[case] x: i32) {}

#[apply(bools)]
#[apply(ints)]
fn testit(q: bool, x: i32) {
    ...
}
```
Or alternatively maybe the apply syntax could work like this:
```rust
#[apply(bools, ints)]
fn testit(q: bool, x: i32) {
    ...
}
```
Would such a thing be possible?

**Comment by la10736** [comment]
This is not supported by `rstest_reuse` and I don't think that I would introduce this feature in this crate: this is just designed to reuse a bunch of test and not as a new dsl to compose a new set of test.

Anyway you can implement this by just `rstest`:

```rust
#[rstest]
fn testit(#[values(true,false)] q: bool, #[values(0,1,2)] x: i32) {
    ...
}
```

In #115 I'll implement templates that cares about `#[values(...)]` attributes but compose them is something diffeent.

**Comment by asomers** [comment]
Ahh, I didn't know you could do that.  Thanks for the tip!

**Comment by jhpratt** [comment]
To add my use case here, I was effectively trying to reuse the `#[values]` attributes between tests, composing as necessary. My current situation is using iterators (which I have turned into fixtures), but this combines them all into a single test — something I'm trying to avoid by switching to `rstest`.

I imagine this would be quite difficult to handle, given there's already quite a bit of trickery going on. But that's my use case.
