### ISSUE TITLE
Error when using &str in cases

### ISSUE THREAD

**Issue by mrahhal** [la10736/rstest#139]
I'm writing a unit test for one of my modules (in the same file). Something like this:

```rs
// The module code. Includes several functions.
// ...

// And then the unit tests.
#[cfg(test)]
mod tests {
    use super::*;
    use rstest::*;

    #[rstest]
    #[case('a', 'b')]
    #[case('c', 'd')]
    fn some_test(#[case] hiragana: char, #[case] expected: char) {
        assert_eq!(expected, some_function_to_test(hiragana));
    }

    // Failing here:
    #[rstest]
    #[case("a", "b")]
    fn another_test(#[case] hiragana: &str, #[case] expected: &str) {
        assert_eq!(expected, another_function_to_test(hiragana));
    }
}
```

The moment I try to use a string in the case (not sure if this might be happening with other types since I haven't tried much) a compiler error shows up. In the snippet above, the second `#[rstest]` is showing me the following:
![image](https://user-images.githubusercontent.com/4404199/157679076-3d39c253-294d-492f-9e67-5901b60106c1.png)

As a workaround, I had to drop `use super::*` and instead import each and every symbol specifically from my module.

Any idea what's going on here?

**Comment by la10736** [comment]
Have you redefined `panic!()` macro in your code?

**Comment by mrahhal** [comment]
Nope, my code does nothing crazy. Maybe it's something in my deps. I'll try and do a small repro in a bit and give you that.

**Comment by mrahhal** [comment]
I just found the problem. I don't remember doing it, but I found that there was this line in my module at the top of the file:
```rs
use core::panic;
```
Might have been added automatically when I was playing with some code, and for some reason it wasn't marked unused.

I removed it and everything is working as expected now.
