### ISSUE TITLE
How to do fixture finalization?

### ISSUE THREAD

**Issue by wizard-28** [la10736/rstest#143]
How do I do fixture finalization, like I can do with [pytest](https://docs.pytest.org/en/7.1.x/how-to/fixtures.html#teardown-cleanup-aka-fixture-finalization)?

**Comment by la10736** [comment]
I thought about this for a while and I didn't find any good way to do it in rust: not from a implementation point of view but on how to define a good syntax for it... I'm waiting for generators in rust but I think that're far for coming in. 

Anyway the best way to do it today in rstest is return a your own fixture type and implement `Drop` trait. Maybe can be useful to implement `Deref` trait too ... is not a good practice use `Deref` to mimic inherit but in tests can be acceptable.

**Comment by wizard-28** [comment]
> I thought about this for a while and I didn't find any good way to do it in rust: not from a implementation point of view but on how to define a good syntax for it... I'm waiting for generators in rust but I think that're far for coming in.
> 
> Anyway the best way to do it today in rstest is return a your own fixture type and implement `Drop` trait. Maybe can be useful to implement `Deref` trait too ... is not a good practice use `Deref` to mimic inherit but in tests can be acceptable.

Thanks for the idea, works!
