### ISSUE TITLE
Full module paths required in `#[template]` case argument definitions

### ISSUE THREAD

**Issue by sandreae** [la10736/rstest#145]
_EDIT: Initial example contained mistake, updated with suitable example._

HI @la10736 , thanks for such a great testing library :+1:

I can't tell if this is the expected behaviour, but it seems counter-intuitive to me, so I wonder if I'm doing something wrong.

When defining a template with cases, I am needing to give full inline module import paths for each case argument, otherwise I get the `cannot find function "x" in this scope` error when applying the templates in another module.

The example below should demonstrate this.

```rust
use rstest_reuse;


#[macro_use]
pub mod template {
    use rstest_reuse::template;


    // Import the function to be used here
    use crate::values::the_number_two;


    // This doesn't work `the_number_two() not found in scope`.
    #[template]
    #[rstest(a,  b, case(the_number_two(), 2), case(4/2, 2))]
    fn template_that_does_not_work(a: u32, b: u32) {}


    // This template imports with the full module path, it works.
    #[template]
    #[rstest(a,  b, case(crate::values::the_number_two(), 2), case(4/2, 2))]
    fn template_that_works(a: u32, b: u32) {}
}


pub mod values {
    pub fn the_number_two() -> u32 {
        2
    }
}


#[cfg(test)]
pub mod test {
    use rstest::rstest;
    use rstest_reuse::apply;


    #[apply(template_that_does_not_work)]
    fn it_does_not_works(a: u32, b: u32) {
        assert!(a == b);
    }


    #[apply(template_that_works)]
    fn it_works(a: u32, b: u32) {
        assert!(a == b);
    }
}
```

Is this the expected behaviour?

**Comment by la10736** [comment]
Sorry.... I'really confused. Can you give me a simple complete example of this behavior? This should not be how it works.

**Comment by sandreae** [comment]
Sorry, I just looked at my first example above and see it's very wrong..... The link above should make it clear, I'll update the initial comment with a better example.

**Comment by la10736** [comment]
Ok, now I've understand.... And... Yes this is the right behavior.

Tests are rendered where are 'applied' and all dependencies should be
reachable from these position. You can use also a local reference but you
should import it where you apply the template... In this case you can use
also a different implementation of your dependencies... In some cases this
can be very useful.

Il lun 9 mag 2022, 15:33 Sam Andreae ***@***.***> ha scritto:

**Comment by sandreae** [comment]
Ah, thanks so much for your reply, interesting with the possibility for using different dependency implementations. Do you have any good examples of this pattern being used?
