### ISSUE TITLE
`use` fixture value from different source file

### ISSUE THREAD

**Issue by poly000** [la10736/rstest#150]
For a bunch of tests sharing the same token(e.g. in SDK tests), write all of them in a single file will make it really big.

**Comment by la10736** [comment]
Can you provide a simple example of what you want to do.... For what I can understand it should already work.

**Comment by poly000** [comment]
> Can you provide a simple example of what you want to do.... For what I can understand it should already work.

Sure.

# token.rs
```rust
#[fixture]
fn access_token() -> String {
    // get `access_token` by calling a web API, e.g.
}
```

# get_name.rs
use token::access_token;
```rust
#[rstest]
fn get_name(access_token: String) {
    // get `name` by calling a web API that need to identify with access_token
}
```

**Comment by la10736** [comment]
https://gist.github.com/la10736/d96fc4326fcc2c0c3d79d835983bec80

Seams to work ... you should use a valid visibility level for your fixtures

**Comment by poly000** [comment]
> https://gist.github.com/la10736/d96fc4326fcc2c0c3d79d835983bec80
> 
> Seams to work ... you should use a valid visibility level for your fixtures

sorry for the false issue...
