### ISSUE TITLE
unused_import warning for rstest_reuse templates exported and only used by other crates

### ISSUE THREAD

**Issue by mauricelam** [la10736/rstest#176]
The following code causes unused_import warning:

```
mod template_module {

    use rstest_reuse::template;

    #[template]
    #[export]
    #[rstest]
    fn my_test_function() {
    }
    
}
```

```
warning: unused import: `my_test_function`
  --> src/main.rs:14:8
   |
14 |     fn my_test_function() {
   |        ^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default
```

Since I am exporting the template for another crate to use, I am not using it within my own crate. But even if there are usages from other dependent crates, this causes the above warning, which I think is caused by `pub(crate) use #macro_name` generated by `rstest_reuse`.

[rustexplorer](https://www.rustexplorer.com/b#%2F*%0A%5Bdependencies%5D%0Arstest%20%3D%20%22*%22%0Arstest_reuse%20%3D%20%22*%22%0A*%2F%0A%0Amod%20template_module%20%7B%0A%0A%20%20%20%20use%20rstest_reuse%3A%3Atemplate%3B%0A%0A%20%20%20%20%23%5Btemplate%5D%0A%20%20%20%20%23%5Bexport%5D%0A%20%20%20%20%23%5Brstest%5D%0A%20%20%20%20fn%20my_test_function()%20%7B%0A%20%20%20%20%7D%0A%20%20%20%20%0A%7D%0A%0Afn%20main()%20%7B%0A%20%20%20%20println!(%22%22)%3B%0A%7D)

**Comment by la10736** [comment]
Right,
I'll try to fix it ASAP by add `#[allow(unused_imports)]`
