### ISSUE TITLE
Generate values list from function

### ISSUE THREAD

**Issue by tmbull** [la10736/rstest#185]
Apologies if this is covered somewhere in the docs or in another issue, but I was unable to find it. Is it possible to generate a values list from a function or range? 

For example, something like this: 

```
    fn should_be_greater_than_0(
        #[values(1..10)]
        size: u64
    ) {
        assert!(size >= 0)
    }
```

or this: 

```
    fn my_args() -> Vec<u64> {
        (1..10).collect::<Vec<_>>()
    }

    #[rstest]
    fn should_be_greater_than_0(
        #[values(my_args())]
        size: u64
    ) {
        assert!(size >= 0)
    }
```

I understand that this does not work because values expects a comma delimited list of arguments, but I'm unsure how (or if it's possible) to generate this programatically. Thanks for the help and the great library!

**Comment by la10736** [comment]
Unfortunately is not possible at all. Procedural macros are executed on parsing stage and receive one block at the time and know nothing about runtime context. In your case `my_args()` is just an expression and in procedural macro context we cannot know what it is supposed to do.

Sorry

**Comment by tmbull** [comment]
@la10736 no problem. In my case, the range of values was relatively small so I just generated the string and pasted it into the values param. But I thought it might be useful to generate arbitrary values. Thanks for the reply and the clarification.

**Comment by maratik123** [comment]
@la10736 But may be it is possible to generate values for tests from `std::ops::Range` and `std::ops::RangeInclusive`?
