### ISSUE TITLE
Consider updating `rstest_macros` to use Syn v2

### ISSUE THREAD

**Issue by LikeLakers2** [la10736/rstest#187]
Hi! [Syn v2 recently released](https://github.com/dtolnay/syn/releases/tag/2.0.0). However, I notice you're still using Syn v1. Perhaps you could consider updating `rstest_macros` to use Syn v2?

Something to consider before doing so: Syn v2's new MSRV is Rust 1.56, moved up from Rust 1.31. Rust 1.56 was released in October 2021, making it a relatively old version. However, `rstest` does not appear to have an MSRV, not even with the [`rust-version` `Cargo.toml` option](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) - so I'm unsure what MSRV you intend `rstest` to have.

You may also have to edit some code to support some of the breaking changes that Syn v2 brings with it.

However, if neither of those are a problem to you, then consider changing your Syn dependency to depend on Syn v2.

**Comment by la10736** [comment]
Thx to report it. I'll do some experiments ASAP and `1.56` it's ok as MSRV. I don't think that the syn breaking changes can be an issue and maybe I'll also switch to 2021 edition.
