### ISSUE TITLE
Add "global" timeout

### ISSUE THREAD

**Issue by aviramha** [la10736/rstest#190]
We often find ourselves adding the same timeout proc macro to each test and would love if we could set it in a global level then override on a function level.
I was thinking of adding `RSTEST_TIMEOUT` environment variable to control it then logic would be if function timeout exists - use that, if not, try to use `RSTEST_TIMEOUT`.

I can send a PR if the idea makes sense.

**Comment by la10736** [comment]
Yes, it have sense.

THX
