### ISSUE TITLE
allow to run individual parametrized test cases from vscode?

### ISSUE THREAD

**Issue by anthrotype** [la10736/rstest#195]
as you know, Visual Studio Code lets one run specific tests (when you hover on a test function it detects it is a test and shows a "Run Test" button above it that will call cargo test with that specific test selected).
When I use rstest with multiple parametrized cases, multiple Run Test labels will appear but they will be all in one line and get easily truncated on the right if there are lots of them and the screen is not wide enough, see:

<img width="1393" alt="Screenshot 2023-04-27 at 18 36 46" src="https://user-images.githubusercontent.com/6939968/234943839-1f9ccda9-1aaa-4a5d-a1e7-15148128febf.png">

Ideally the "Run Test" button would appear right above each `#[case(...)]` attribute.

I noticed this because I was previously using https://github.com/foresterre/yare to do the parameterized testing and for that one, somehow, vscode can identify the sub-tests and show distinct Run Test buttons above each case definition, e.g.:

![image](https://user-images.githubusercontent.com/6939968/234945343-905c820b-9ead-48e5-b0c2-9403a671ae5a.png)

I am a newbie and have no idea how these procedural macros even work, but wanted to ask in case anybody knows more, feel free to close thanks.

**Comment by la10736** [comment]
`rstest` doesn't have any control over it. The parameterized test cases are
desugared as a test module that contains some tests functions (I'm
simplifying it). Maybe vscode can move gutter icons aside the case
attribute but should introduce a `rstest` specific hook... I don't think
they will do it.

Il giorno gio 27 apr 2023 alle ore 19:41 Cosimo Lupo <
***@***.***> ha scritto:
