### ISSUE TITLE
Inject case description?

### ISSUE THREAD

**Issue by hillin** [la10736/rstest#200]
I'm imagining something like the `#[case_desc]` as demonstrated below could be helpful for debugging/tracing:

```rust
#[rstest]
#[case::foo(1)]
#[case::bar(2)]
fn test(#[case_desc] case_desc: &str, #[case] value: isize) {
  println!("Running test '{}', value = {}", case_desc, value);
  match value {
     1 => { assert_eq!("foo", case_desc); }
     2 => { assert_eq!("bar", case_desc); }
     _ => {}
  };
}
```

**Comment by la10736** [comment]
Ok... is a good idea.I've already traced this issue in #177 . You can update it and close this ticket. I'm not sure if is better just narrow the syntax to the description as you proposed or a more general approach like `#[context]`... or even both.

**Comment by hillin** [comment]
Yeah, I think the `#[context]` approach is good enough for me.
