### ISSUE TITLE
vscode/rust-analyzer "debug overlay action" not working anymore

### ISSUE THREAD

**Issue by curiousmindflow** [la10736/rstest#223]
Hello,

First of all, thank you for this great crate, it's my main test crate for each of my projects :)

# Main Issue
Here is my problem, i noticed today that i was not able anymore to run/debug my rstest though rust-analyzer "overlay actions", like we can see below.
![rstest_vscode_overlay_actions](https://github.com/la10736/rstest/assets/35933098/5ac2d7e1-8b77-4841-a7f0-278b8b7d2d0e)

Some times ago, there was other "actions" in overlay, one for each case/values. It's no more here.

## Run test
When i click on "Run test" this command is executed by vscode:
```shell
cargo test --package nodus-rtps --lib -- behavior::writers::writer::tests::send_gap --exact --nocapture
```
The test name is not exact, it should have been "behavior::writers::writer::tests::send_gap::case_1::reliability_level_1_ReliabilityKind__Reliable"

For the suffixes:
- case_1: because it's the first case
- reliability_level_1_* : because i have a #[values(...)] macro on a parameter

## Debug
When i click on "Debug" this command seems to search the test, as the Run test, but because it's not found, no debug is started

# Second Issue
With the "Rust Test Explorer", i can see the correctly found suffixes:
![rstest_vscode_test_explorer](https://github.com/la10736/rstest/assets/35933098/94c49a76-74a6-482e-9c6e-10aaccff07d7)

I can run the test from there, on hover there is a "Run" button, works fine.
But there is also a button to debug the case, and this is not working. When i click on it, vscode is telling me:
"Error while debugging test: Error: Method not implemented".
Maybe it's "Rust Test Explorer" side.

# Summary
The correct behavior of the "overlay actions" was very comfortable and allowed very quick run/debug for each test/case/value.
Now, i don't have other option than setup a standard debug configuration in vscode and change the unit test name each time i want to debug a un

# Environement
- vscode
![image](https://github.com/la10736/rstest/assets/35933098/4af15e14-01b6-446b-a70b-faa202d4a97b)
- rust-analyzer extension: v0.3.1713
- Rust Test Explorer: v0.11.0
- rust channel of the project: 1.73.0 stable, x86_64-unknown-linux-gnu

**Comment by la10736** [comment]
Thx for reporting it but both of them are not `rstest` issues... I have no control over vscode overlay implementation or tests explorer.

Anyway it seams a vscode's regression that just show the button for the test module `behavior::writers::writer::tests::send_gap` but the single tests inlays was disappeared ... You should ask to the vscode guys
