### ISSUE TITLE
Please clearly state the MSRV in the README and documentation and use the "rust-version" flag.

### ISSUE THREAD

**Issue by iddm** [la10736/rstest#227]
This really, really helps to figure out what's wrong when cargo doesn't want to find the appropriate package on older (incompatible) rust versions.

**Comment by la10736** [comment]
You're right.
I'll try to address it ASAP.... but I don't know how to compute it. Is there any tools to do it?

**Comment by iddm** [comment]
Usually I figure it during the development lifecycle: one of the dependencies no longer builds after an update and requires a new version, or I need a new version from the Rust compiler myself and so need to bump it. Retroactively, as in this case with rstest, I think only trial and error will work. I updated from 0.13 to 0.18 and I can't build with 1.56 any longer. So something in between should work, I guess. If I figure it out earlier than you, I'll post it here or create a PR.
