### ISSUE TITLE
feat: provide a cargo feature to disable the proc macro inference in #221

### ISSUE THREAD

**Issue by rbtcollins** [la10736/rstest#258]
Reading Cargo.toml during compilation is problematic - there isn't necessarily a Cargo.toml to read.  This was added in #221 

For us, we build with Bazel, and do happen to have a Cargo.toml, but it isn't copied into the build environment - because rustc doesn't typically need it. And indeed with about 1000 crates in use, this 0.20 update of rstest is the first we've encountered it.

**Comment by la10736** [comment]
Ok, I've suspected this issue but l I've undervalued it. I'll add a feature flag for it disabled by default ASAP.

**Comment by la10736** [comment]
I choose to add the feature `crate-name` but enabled by default: you can disable this feature with:

```toml
rstest = { version = "0.21.0", default-features = false }
``` 

The `0.21.0` version will be on-line soon.
