### ISSUE TITLE
Mixing `#[rstest]` and `#[serial]` breaks VS Code's IntelliSense with rust-analyzer

### ISSUE THREAD

**Issue by mtilda** [la10736/rstest#262]
### Background

I am using the crates [rstest](https://docs.rs/rstest) and [serial_test](https://crates.io/crates/serial_test).

VS Code's IntelliSense stops working when I define a test function with both `#[rstest]` and `#[serial]`.

[IntelliSense](https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_intellisense) is a VS Code feature (or rather a collection of features) that provide suggestions, information about symbols, and navigational tools.

The VS Code extension [rust-analyzer](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer) provides support for the Rust language.

The root cause of this problem could be any one of the above mentioned technologies. Let me know if you think this issue does not belong on this repository.

### Steps to reproduce

1. Install VS Code (I am on version 1.90.1)
1. Install the extension [rust-analyzer](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer) (I am on version v0.3.2002)
1. Install Rust (I am on 1.78.0)
1. Use the command `cargo init` to create a new cargo package.
1. Add the necessary dependencies with the command `cargo add rstest serial_test`; or if you want the same versions as me, use the command `cargo add rstest@0.21.0 serial_test@3.1.1`
1. Open VS Code
1. Paste this in `src/main.rs`:

    ```rs
    mod tests;
    
    fn main() {
        println!("Hello, world!");
    }
    ```

1. Create `src/tests.rs` with the following content:

    ```rs
    #[cfg(test)]
    mod tests {
        use rstest::rstest;
        use serial_test::serial;
    
        #[rstest]
        fn test_a() {
            // IntelliSense works here
            let _example = vec![1,2,3];
        }
    
        #[test]
        #[serial]
        fn test_b() {
            // IntelliSense works here
            let _example = vec![1,2,3];
        }
    
        #[rstest]
        #[serial]
        fn test_c() {
            // IntelliSense does not work here
            let _example = vec![1,2,3];
        }
    }
    ```

### Expected behavior

* Between `_example` and `=`, We should expect to see the inferred type `Vec<i32>`.
* Hover your mouse over the `_example` in each test function. We should expect to see a [Peek](https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_peek).
* Type a `.` after `vec![1,2,3]` and before the `;`. We should expect to see a drop down of suggestions (see screenshots).

### Screenshots

![IntelliSense working inside test_a](https://github.com/palfrey/serial_test/assets/63630918/14e1d482-2fe7-4ed9-a86e-bcb7dd1578f1)

![IntelliSense working inside test_b](https://github.com/palfrey/serial_test/assets/63630918/d006bc88-8d04-4703-964a-4e19427dab7e)

![IntelliSense not working inside test_c](https://github.com/palfrey/serial_test/assets/63630918/64c3a573-8df2-4e7f-93bd-69a61aa3efe1)

**Comment by mtilda** [comment]
Cross-posted: https://github.com/palfrey/serial_test/issues/112#issue-2360631238

**Comment by la10736** [comment]
I'm guessing that you posted the issue in the wrong places: It seams more a rust-analyzer issue instead. There's nothing we can do for fix it: from our point of view everything work well:

```text
mdamico@miklap:~/dev_random/rstest_262$ cargo test
   Compiling rstest_262 v0.1.0 (/home/mdamico/dev_random/rstest_262)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.20s
     Running unittests src/main.rs (target/debug/deps/rstest_262-1caee84ec4ffcd71)

running 3 tests
test tests::test_a ... ok
test tests::test_b ... ok
test tests::test_c ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

**Comment by mtilda** [comment]
@la10736 thanks for the quick reply!

Yesterday, per your suggestion, I opened https://github.com/rust-lang/rust-analyzer/issues/17458

Now fixed by: https://github.com/rust-lang/rust-analyzer/pull/17462
