### ISSUE TITLE
Using `${ENV_VAR}` environment variables in `#[files]` possible?

### ISSUE THREAD

**Issue by hansl** [la10736/rstest#276]
I have a test suite of JavaScript files that I really cannot put in my repo (it's the WPT, which a shallow clone can take a gigabyte). Unfortunately, that means that I would have `#[files()]` that point to files outside my repo, which I also don't like much.

Would it be possible to use an environment variable in the path so people can provide the path to their local copy of those suites?

Users running the rstests would have opted-in using a feature flag. If that environment variable is not set, it'd be okay with me to just panic (with a friendly message of course).

If this is something that could be done and the maintainers are interested, I can make the PR for it. Let me know.

**Comment by la10736** [comment]
Seams interesting. Maybe the best could be use some kind of template engine that map environment variables .  Or simple use handlebars syntax driven by env variables.

Anyway, also a simple replace of `${ENV_VAR}` is nice. Let me know if need some help.

Can you sketch here a syntax and some example before starting?

**Comment by hansl** [comment]
@la10736 See my PR (#277) for an example. It's fairly straightforward.
