### ISSUE TITLE
Include LICENSE files in the published rstest crates

### ISSUE THREAD

**Issue by danakj** [la10736/rstest#278]
While the Cargo.toml specifies a license (or licenses), crates also typically include a copy of that license (or licenses) as LICENSE files. This github repo contains the license files but the `rstest`, `rstest_macros` and `rstest_reuse` crates do not.

Can the appropriate license files be included in the these crates?

As a consumer of third party open source libraries, Chromium is aiming to ensure we include the license files in our own source tree for all of our third-party dependencies, and the rstest crates are three of the few for which they are missing. Chromium issue: [crbug.com/369075726](https://crbug.com/369075726)

**Comment by la10736** [comment]
There are links.... Is that an issue? I guess that maybe you use some kind of script that cannot get this case.

The published code contains the license files
- https://docs.rs/crate/rstest/latest/source/
- https://docs.rs/crate/rstest_macros/latest/source/
- https://docs.rs/crate/rstest_reuse/latest/source/

**Comment by danakj** [comment]
Ah, we're on 0.17 but they have become added to the rstest crate since:
```
% wget -q https://crates.io/api/v1/crates/rstest/0.17.0/download -O rstest.tgz && tar tfz rstest.tgz |grep LICENSE
% wget -q https://crates.io/api/v1/crates/rstest/0.22.0/download -O rstest.tgz && tar tfz rstest.tgz |grep LICENSE
rstest-0.22.0/LICENSE-APACHE
rstest-0.22.0/LICENSE-MIT
```

The `rstest_macros` and `rstest_reuse` crates also have them now:
% wget -q https://crates.io/api/v1/crates/rstest_macros/0.22.0/download -O rstest.tgz && tar tfz rstest.tgz |grep LICENSE
rstest_macros-0.22.0/LICENSE-APACHE
rstest_macros-0.22.0/LICENSE-MIT

% wget -q https://crates.io/api/v1/crates/rstest_reuse/0.7.0/download -O rstest.tgz && tar tfz rstest.tgz |grep LICENSE
rstest_reuse-0.7.0/LICENSE-APACHE
rstest_reuse-0.7.0/LICENSE-MIT
```

Thanks :) We'll roll and pick up the new versions.
