### ISSUE TITLE
`OnceLock` is stabilized in 1.70.0 but current MSRV is 1.67.1

### ISSUE THREAD

**Issue by rnbguy** [la10736/rstest#284]
#237 introduces the use of `OnceLock`

https://github.com/la10736/rstest/blob/9df2cc1903abc5c29c932e6f5f122af4a7b9e160/rstest_macros/src/render/fixture.rs#L25-L26

But `OnceLock` is [stabilized in 1.70.0](https://doc.rust-lang.org/stable/src/std/sync/once_lock.rs.html#102). Shouldn't the MSRV of `rstest` be 1.70.0 ?

**Comment by la10736** [comment]
You're right :cry:

I trusted `cargo hack check --rust-version --workspace --ignore-private` but maybe it use just the provided msrv from the other packages.... I need to change it.

Thank to report it
