### ISSUE TITLE
Matrix version of rstest_parametrize

### ISSUE THREAD

**Issue by KSXGitHub** [la10736/rstest#38]
this code:

```rust
#[rstest_matrix(
  foo => [0, 1, 2],
  bar => ['a', 'b'],
)]
fn mytest(foo: i32, bar: char) {
  // ...
}
```

should be equivalent to this code:

```rust
#[rstest_parametrize(
  foo, bar,
  case(0, 'a'),
  case(1, 'a'),
  case(2, 'a'),
  case(0, 'b'),
  case(1, 'b'),
  case(2, 'b'),
)]
fn mytest(foo: i32, bar: char) {
  // ...
}
```

**Comment by la10736** [comment]
Wow ... I missed it. I like it.

But I should schedule it after the next release.

**Comment by la10736** [comment]
As noted in #42 I can try to use just `rstest()` macro to do this job.

maybe is better to open a new ticket that describe this syntax.

**Comment by la10736** [comment]
Done. Now it use `rstest_matrix` but I wold implement #42 before shipping next release and maybe `rstest_matrix` alone syntax will never released.

**Comment by svenstaro** [comment]
How about a release? I'd really like to use this but would prefer not to use git versions.

**Comment by la10736** [comment]
@svenstaro You call me for a release every time!!! :)
Thanks for that. I'm working on fixture injecting (with partial parameters)... but I'm just refactoring so I can merge it soon.

If you use this feature can you send me a real life example?... I'm stuck on it and I would like replace the synthetic one in docs.

**Comment by svenstaro** [comment]
Yeah so [here](https://github.com/svenstaro/dummyhttp/blob/master/tests/requests.rs#L50) I would like to have a matrix with N codes and M methods, for instance.
