### ISSUE TITLE
Can you do an intermittent release?

### ISSUE THREAD

**Issue by svenstaro** [la10736/rstest#40]
I currently can't publish my crate because I really want to use `?` inside `#[rstest]` tests but that only works with the git version. Could you publish a new version that only has those new compatibility changes?

**Comment by la10736** [comment]
I'll do my best to publish it till the end of the week. Is it ok for you?

**Comment by svenstaro** [comment]
Sure, that'll work!

**Comment by la10736** [comment]
Hi @svenstaro can you help me by check documentation? If it is ok get git version and use 
```
cargo doc --open
```
to compile and show documentation.... English is not my forte and I need another eye pair to check it... Thanks

**Comment by svenstaro** [comment]
@la10736 Ok, doing this right now.

**Comment by svenstaro** [comment]
Can I have my release now? :)

**Comment by la10736** [comment]
Yes... `rstest` 0.3.0 is out NOW!! I'm in Florence at RustLab conference. But I'm really happy to do it right now.

Thanks for your help and this great motivation to close it.
