### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by la10736** [la10736/rstest#46]

**Comment by sivakov512** [comment]
Hi! Thank you for awesome crate!

Can I help you with this issue?

**Comment by la10736** [comment]
Yes... OF COURSE!!!
You're welcome!

**Comment by sivakov512** [comment]
Okay. But I can only write config for CI, I can't setup CI for your repo, because I have no permissions for it.

**Comment by la10736** [comment]
Ok.. write it and make PR with the instructions to enable it and I'll do it

**Comment by la10736** [comment]
Ok, I forgot that test depends on `cargo-edit` (`cargo install cargo-edit`) ... that's should be not a problem for CI environment  but I'll remove this odd and hide dependency as soon as possible #61

**Comment by svenstaro** [comment]
You should apply to GitHub Actions to ease the pain a little. It's much faster than Travis in my experience.

**Comment by la10736** [comment]
Basic CI functionalities now are in place. Improvements will come later.
