### ISSUE TITLE
Make tags for releases

### ISSUE THREAD

**Issue by svenstaro** [la10736/rstest#54]
Currently, it's a bit hard to figure out which cargo release maps to which git commit. It would be nice if you made tags for that.

**Comment by la10736** [comment]
Hi, I'm not sure which kind of tags you would like. I realized now that I forget to tag 0.3 release (damn) but what do you mean with _cargo release_? AFAIK rstest should not have any dependency from `cargo` version... it should depends just to toolchain version.

I forgot something?

**Comment by svenstaro** [comment]
It doesn't seem like there are any tags: https://github.com/la10736/rstest/tags

Am I missing something?

**Comment by la10736** [comment]
You don't miss anything. I fond now that I tagged the wrong commit in a sub dir (f**k).

Now the 0.3.0 should be ok. It' s Ok for you or is better if I try to identify all 2.* releases?

**Comment by svenstaro** [comment]
It's fine if you do this from now on. Thanks. :)
