### ISSUE TITLE
Document rstest_matrix in the README

### ISSUE THREAD

**Issue by svenstaro** [la10736/rstest#63]
Currently, you get the impression that what the README talks about is basically the extent of this library which isn't quite true. There's also `rstest_matrix`. I think it's such a cool feature that it should also be documented.

**Comment by la10736** [comment]
My first idea was that README should be small and sharp: just illustrate the most important features in just one page. But maybe I was wrong, not too much people go to docs and maybe never know about other features.
The things are more clear now that the docs are broken.

I've planned to change the things in the next release where I'll have just `rstest` and I can illustrate all features by just one example.

But I'll try to expand the README in a 0.4.2 release.

Thanks for your feedback.

**Comment by svenstaro** [comment]
Well, I think the README should provide an overview of the most important features and I think this is one of them.

**Comment by la10736** [comment]
Did it
