### ISSUE TITLE
Docs seem broken

### ISSUE THREAD

**Issue by svenstaro** [la10736/rstest#65]
Going to https://docs.rs/rstest we see `rstest-0.4.1 doesn't have any documentation.` but that's not true. Something is weird. Maybe it's a problem at docs.rs site?

**Comment by la10736** [comment]
It's a docs.rs bug rust-lang/docs.rs#422

I'm waiting that the docs.rs guys fix it and then try to publish it again.

**Comment by la10736** [comment]
Deploy docs on github as workaround. A folder for each version and a trunk one. Deploy the trunk one by github action... is it possible?

**Comment by la10736** [comment]
Closed via https://github.com/rust-lang/docs.rs/issues/422#issuecomment-563149296
