### ISSUE TITLE
Backtrace loses code location in macro

### ISSUE THREAD

**Issue by msarahan** [la10736/rstest#66]
My apologies if this is already in another issue and I've just missed it.  I did look, but I might lack the vocabulary as a newbie.

I have used rstest (which I am very excited about) to replace a loop over a list (https://github.com/msarahan/version-compare/blob/polymorph_parts/src/test/test_version_set.rs#L14 and https://github.com/msarahan/version-compare/blob/polymorph_parts/src/version_compare.rs#L94) with parametrized tests (https://github.com/msarahan/version-compare/blob/rstest/src/test/macros.rs#L44 and https://github.com/msarahan/version-compare/blob/rstest/src/version_compare.rs#L89)

In doing so, my backtraces seem to lose any relevant line number references.  They are replaced with lines in the macro instead:

```
   8: std::panicking::begin_panic_fmt
             at src\libstd/panicking.rs:339
   9: version_compare::version_compare::tests::compare
             at src/lib.rs:1
  10: version_compare::version_compare::tests::compare::case_11
             at src\test/macros.rs:94
  11: version_compare::version_compare::tests::compare::case_11::{{closure}}
             at src\test/macros.rs:46
  12: core::ops::function::FnOnce::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libcore\ops/function.rs:235
```

Is there any way to preserve the reference to the original code location in my tests?

**Comment by la10736** [comment]
Hi, I'm very exciting to see how `rstest` could be used and what patterns can emerge!

I never thought to this approach to make parametrized cases reusable!

Now, for your issue, I guess that is because you define your tests function in your macro by pass it as item. You can try to define the function out of your macro and just pass the function name (`Ident`) to the macro that can define a _new function_ that just wrap the call. That should give a correct trace inside your test.

For instance
```rust
    fn compare(a: &str, b: &str, operator: &CompOp) {
        match VersionCompare::compare(a, b) == Ok(operator.clone()) {
            false => panic!(),
            _ => {}
        }
    }

parametrize_versions_set!(compare)
```
And in your macro

```rust
macro_rules! parametrize_versions_set {
    ( $test:ident ) => {
        #[rstest_parametrize(a,  b, operator,
        case::equal_strings("1", "1", &CompOp::Eq),
        case::more_zeros_left("1.0.0.0", "1", &CompOp::Eq),
        ...,
        )]
        fn concat_idents!(__inner_macro_, $test)(a: &str, b: &str, operator: &CompOp) {
            $test(a, b)
        }
```
The downside here is that you need to repeat the function signature in your macro. Maybe we can do better, but now I haven't any other idea.

**Comment by la10736** [comment]
Any update on it? Can I close it?

**Comment by msarahan** [comment]
Your suggestion makes a lot of sense - thank you for thinking about it.  I haven't had time to hack on this, so I can't say if it works, but I absolutely intend to try it.  I think we can/should close the issue, but I'll still follow up when I get a chance to try it.

**Comment by msarahan** [comment]
Found time to return to this.  Can I run a few questions by you?  I looked up concat_idents, and it seems like it's not really the preferred method to do this: https://github.com/rust-lang/rust/issues/29599

A comment in there linked me to paste: https://github.com/dtolnay/paste which seems like it'll do the trick when I figure out how to use it.

For `__inner_macro_`, I think you mean for me to use this crate: https://docs.rs/inner/0.1.1/inner/

What goes into that macro?  Is the "inner" macro how the values get injected, or is it just a convenience wrapper to return an unwrapped return from the function?

**Comment by la10736** [comment]
Ok, I admit that I didn't try the answer before post it :smile:. I wrote in in the bus while going to work... Like now :smile:. 
For your first question you are right, concat_idents just not work, paste! seams the right one.
For the second question __inner_macro is just a prefix to prevent function name clashing... But maybe it's better to find something else because this will be the name of your test.
Later in the morning I'll return on it to try to write an example.

**Comment by la10736** [comment]
Unfortunately `paste::item!` doesn't work with procedural macro annotation so I have modified the solution by add an output name... I don't like it but I should investigate it more by do some tests on `paste` crate.

try to use something like follow

```rust
pub fn compare(a: u32, b: u32) -> bool {
    return a == b;
}

#[cfg(test)]
mod tests {
    use super::*;
    use rstest::*;

    macro_rules! parametrize_compares {
        ( $name:ident, $test:ident ) => {
            #[rstest_parametrize(a,  b,
                case(2, 2),
                case(2, 4/2),
                case(4/2, 2),
            )]
            fn $name (a: u32, b: u32) {
                $test(a, b)
            }
        }
    }

    fn it_works(a:u32, b:u32) {
        assert!(compare(a, b));
    }

    fn it_fail(a:u32, b:u32) {
        assert!(!compare(a, b));
    }

    parametrize_compares!(ok, it_works);
    parametrize_compares!(fail, it_fail);
}
```

**Comment by la10736** [comment]
I don't understand what I did wrong before, but now  I can do it without introduce a new name:

```rust
pub fn compare(a: u32, b: u32) -> bool {
    return a == b;
}

#[cfg(test)]
mod tests {
    use super::*;
    use rstest::*;

    macro_rules! parametrize_compares {
        ( $test:ident ) => {
            paste::item! {
                #[rstest_parametrize(a,  b,
                    case(2, 2),
                    case(2, 4/2),
                    case(4/2, 2),
                )]
                fn [< _ $test >] (a: u32, b: u32) {
                    $test(a, b)
                }
            }
        }
    }

    fn it_works(a:u32, b:u32) {
        assert!(compare(a, b));
    }

    fn it_fail(a:u32, b:u32) {
        assert!(!compare(a, b));
    }

    parametrize_compares!(it_works);
    parametrize_compares!(it_fail);
}
```

**Comment by msarahan** [comment]
This works beautifully!  Thank you so much for helping me through this.  I'm still a rust beginner, but I hope I'll be able to help improve rstest over time.  I really, really hope rstest can be as simple and powerful as pytest someday.  Maybe not totally possible, given the very different language requirements, but I think you've dramatically improved testing on Rust, regardless.
