### ISSUE TITLE
Add a trivial support for async tests

### ISSUE THREAD

**Issue by la10736** [la10736/rstest#73]
The idea could be to wrap the user function call into `task::block_on()` from `async-std`

Maybe later we can give a way to instantiate a runner or configure some other runtime... but just this hack should give a simple way to test async function directly.

**Comment by svenstaro** [comment]
I'd very much like this to be implemented as this is currently blocking me from writing nice parametrized async tests. :)

**Comment by la10736** [comment]
Ok, you're my best customer....I see to plan it ASAP :)

**Comment by svenstaro** [comment]
Haha :D Well it's a super neat library ;)

**Comment by la10736** [comment]
Ok, both `tokio` and `async-std` have its own `test` attribute to implement async test, but in both cases this option is feature gated and not included by default.

Now `test` attribute in `async-std` is just the same the one I've described in the first comment; but in `tokio` the things are more complicated (that's not a surprise :smile:) and `test` attribute can receive some useful arguments.

So I chose to implement it by use `test` attribute because is more generic and don't try to duplicate code from `async-attribute` and `tokio-macros`, otherwise if I just use `block_on()` change it later to use attribute will introduce a break change. 

Now I'll implement just the `async-std` support but later I can introduce a feature gated `tokio` support too .

**Comment by la10736** [comment]
TODO:
- [ ] end to end test for matrix/parametrized case (should already works)
- [ ] Add unit tests
- [ ] Docs
- [ ] Little refactoring (maybe I need a builder for single test render)
- [ ] Change log

**Comment by la10736** [comment]
Done

**Comment by svenstaro** [comment]
Amazing. I'll test it right away.
