### ISSUE TITLE
Panic and non-panic test cases

### ISSUE THREAD

**Issue by sharksforarms** [la10736/rstest#82]
Hello! I'd like be be able to mix panic and non panic test cases, for example in `test-case` crate: https://github.com/frondeus/test-case/blob/master/README.md#panicking-test-cases-since-100

Would this be possible in rstest?

**Comment by la10736** [comment]
Not yet.
I'd never thought to implement this feature. My idea is that a parametrized test should be coherent in all test cases and the test name should describe a common behavior. But if I think that I never use this feature doesn't mean that it cannot be useful.

My first attempt to find a good syntax to express this case is to accept attributes before `case()` that will be used in just this case.

```rust
#[rstest(a,
    case::this_pass(42),
    #[should_panic]
    case::this_panic(-1)
  )
]
fn my_test(a: i32) {
    if(a<0) {
        panic!("this panic");
    }
}
```
But I'm not sure we can write nested attributes... :confused: ... I'll try it.

**Comment by sharksforarms** [comment]
You're right it could be seen as a bit of an edge case, especially for unit tests where you're testing a small unit of code you could assert on a `Result`. The use-case is for more involved tests like integration where there's multiple areas which could fail depending on the input.

**Comment by la10736** [comment]
Ok, I did some experiments and I can implement it as described before.

I'll implement it next week. Thx

**Comment by la10736** [comment]
Missed:

- [ ] Docs
- [ ] Change log

**Comment by sharksforarms** [comment]
Thanks! Great work on this crate

**Comment by oren0e** [comment]
I don't see this feature in the current docs, is it still available?

**Comment by la10736** [comment]
Yes, of course. https://docs.rs/rstest/latest/rstest/attr.rstest.html#use-specific-case-attributes
