### ISSUE TITLE
Define #[future] attribute to remove `Future` boilerplate

### ISSUE THREAD

**Issue by la10736** [la10736/rstest#98]
Every time an argument (test or fixture) is marked by `#[future] attribute wrap type `T` by `impl std::future::Future<Output = T>`

**Comment by raffomania** [comment]
Hey, do you have an idea on how this might be possible? 
We just tried to solve this with our own type alias, but you can't use those together with `impl` yet.

**Comment by la10736** [comment]
I'm working on #111 now. Unfortunately in the last week ends I was very busy ... I'll implement this feature as the next one.

**Comment by svenstaro** [comment]
Alright that sounds great! Thanks. rstest continues to be awesome, I use it in pretty much all of my projects.

**Comment by la10736** [comment]
Ok, I cannot use `#[asyc]` because `async` is a keyword. Use `#[future]` instead

**Comment by la10736** [comment]
Basic implementation is in place.

What's missed:

- [ ] Integrations test for tests
  - [ ] Cases
  - [ ] Values
  - [ ] Single
- [ ] Unit tests
- [ ] Discard invalid cases like `impl` or some other _strange_ types
- [ ] Little refactoring 
- [ ] Documentation
- [ ] Changelog

**Comment by la10736** [comment]
I've released 0.9.0 yesterday.

**Comment by svenstaro** [comment]
Working perfectly for us, thanks!
